# Generated by Django 2.2.1 on 2019-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reporter',
            name='categories',
            field=models.ManyToManyField(to='reporters.Category'),
        ),
    ]
