# Generated by Django 2.2.1 on 2019-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0003_auto_20190608_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
